// Generated by Wrangler by running `wrangler types --config=wrangler.production.jsonc --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 56352cbd385558eba04c2590b531ef6d)
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
